### ISSUE TITLE
Update kodi repo 

### ISSUE THREAD

**Issue by erudisch** [segler-alex/kodi-radio-browser#10]
How to update the repo to install the new addon version from it? Or is it done automatically by just increasing the addon version?

Regards
Erik

**Comment by erudisch** [comment]
Hello

I've opened this pr https://github.com/xbmc/repo-plugins/pull/2196. It includes https://github.com/segler-alex/kodi-radio-browser/pull/11 and https://github.com/segler-alex/kodi-radio-browser/pull/12.

Can you approve it or you close it and do a own pr to the repo-plugin after the two open prs are merged.

Thank you

**Comment by erudisch** [comment]
Ok, I think everything is fine with the repo pr xbmc/repo-plugins#2196. So could you approve it, please?

**Comment by erudisch** [comment]
Your welcome and thanks for your pre-work and your approval in advance :-)

**Comment by segler-alex** [comment]
i approved as a message on the thread you posted. is this enough?

**Comment by erudisch** [comment]
Hm, don't know. I've never done that before. If not I will ask them what to do. Yet the easiest way would be to close my pr and you open a new one, then everything would be fine, because you are the maintainer.

Regards
Erik
