### ISSUE TITLE
Crashes Kodi

### ISSUE THREAD

**Issue by gerroon** [segler-alex/kodi-radio-browser#2]
I am getting Kodi crashed with this addon whenever I try to plauy from radio browser

PICTURE::LoadImageFromMemory: Unable to determine image type.PICTURE::LoadImageFromMemory: Unable to determine image type.PICTURE::LoadImageFromMemory: Unable to determine image type.PICTURE::LoadImageFromMemory: Unable to determine image type.libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault (core dumped)

I am using Kodi on Debian Testing.

thnx

**Comment by erudisch** [comment]
This is more than two years old, Is it still relevant or could we close it?
