### ISSUE TITLE
[information] new radio browser desktop client

### ISSUE THREAD

**Issue by h3298** [segler-alex/kodi-radio-browser#6]
Radio Browser client for Windows, Mac, Linux
https://github.com/odioapp/odio

**Comment by erudisch** [comment]
This is not a forum or newsletter or anything else. Could we close this issue, please?

**Comment by h3298** [comment]
@erudisch - I just thought it would be helpful for testing purposes and users of Radio Browser might appreciate a cross-platform client (since Kodi is also a cross-platform client.)  I became accustomed to other Github projects where on-topic discussions are permitted,* and did not realize this would offend anyone.

*example: https://github.com/StreisandEffect
